function [Thetainfo] = VBM(Estinfo,Thetainfo,FieldMatrices,Constants,Basis,spikes,Estmu,Estprec,Estcovariates)

SigmaW = diag(1./Thetainfo.precisionest)*FieldMatrices.W;
d = Constants.d;
dt = Constants.dt;
N = Constants.N;


%Estimate theta
v = zeros(d,1);
for i = 3:Constants.N-2
    v(:,1) = v(:,1) + dt*inv(SigmaW)*(Estinfo(i).xestRTS - Estinfo(i-1).xestRTS);
end
vartheta = SigmaW./dt^2/(Constants.N-4);
thetaest = vartheta*v;
Thetainfo.thetaest = thetaest;
Thetainfo.vartheta = vartheta;

%Estimate precision
alpha = 320;
beta = 20;

precest = repmat(1/(0.25^2),Basis.nx,1);
varprec = repmat(0,Basis.nx,1);
if Estprec == 'y'
    % Diagonal estimation
    for j = 1:Basis.nx
        k1 = 0;
        for i = 3:N-2
            k1 = k1+ Estinfo(i).W(j,j) + Estinfo(i-1).W(j,j) + dt^2*(vartheta(j,j) + thetaest(j)^2) ...
                - 2*Estinfo(i-1).S(j,j) + 2*dt*thetaest(j)*Estinfo(i-1).xestRTS(j) ...
                - 2*dt*thetaest(j)*Estinfo(i).xestRTS(j);
        end
        alpha0 = alpha + (Constants.N-4)/2;
        beta0 = beta + k1/2;
        precest(j) = alpha0/beta0;
        varprec(j) = alpha0/beta0^2;
    end
    Meanprecmat = diag(precest);
    
    %Whole Wishart distribution
    dofprior = 1000;
    Prevmatprior = 16/dofprior*eye(Basis.nx);
    Gamma = 0;
    for i = 3:N-2
        Gamma = Gamma + Estinfo(i).W + Estinfo(i-1).W + vartheta + thetaest*thetaest' ...
            - Estinfo(i-1).S - Estinfo(i-1).S' ...
            - Estinfo(i).xestRTS*thetaest' - thetaest* Estinfo(i).xestRTS'  ...
            + Estinfo(i-1).xestRTS*thetaest' + thetaest*Estinfo(i-1).xestRTS';
    end
    Precmatpost = inv(inv(Prevmatprior) + Gamma);
    Meanprecmat = (dofprior + N-4)*Precmatpost;
end

%Estimate mu (Convergence not assured due to identifiability)
if Estmu == 'n'
    Thetainfo(1).muest = -3.5;
    Thetainfo(1).varmu = 0;
else
    muprior = 0;
    Sigmamuprior = 10;
    totalspikenum = 0;
    totalvoidsum = 0;
    phitemp = zeros(Constants.J,Constants.J,Basis.nx);
    for i = 3:N-2
        Umean = sum(multiprod(Basis.phi,reshape(Estinfo(i).xestRTS,1,1,Basis.nx)),3);
        MySigma = Estinfo(i).PRTS; %CHANGE TO FULL COVARIANCE
        for j = 1:Basis.nx
            phitemp(:,:,j) = sum(multiprod(Basis.phi,reshape(MySigma(:,j),1,1,Basis.nx)),3);
        end
        phisigma = sum(phitemp.*Basis.phi,3);
        totalvoidsum = totalvoidsum + dt*Constants.ds^2*sum(sum(exp(beta*Umean + beta^2*phisigma./2)));
        totalspikenum = totalspikenum + size(spikes(i).Coords,1);
    end
    fmu = @(mu) -(-(mu - muprior)^2/(2*Sigmamuprior) + mu*totalspikenum - exp(mu)*totalvoidsum);
    gradfmu = @(mu) -(-mu/Sigmamuprior + totalspikenum - exp(mu)*totalvoidsum);
    options = foptions;
    % options(9) = 1;
    Thetainfo(1).muest = scg(fmu,muprior,options,gradfmu)';
    Thetainfo(1).varmu = 1/(1/Sigmamuprior + exp(Thetainfo(1).muest)*totalvoidsum);
end

%Estimate covariates
if Estcovariates == 'n'
    Thetainfo(1).b(1) = 0;
    Thetainfo(1).b(2) = 0;
    Thetainfo(1).b(3) = 0;
    Thetainfo(1).b(4) = 0;
    Thetainfo(1).b(5) = 0;
    Thetainfo(1).b(6) = 0;
    Thetainfo(1).b(7) = 0;
    Thetainfo(1).b(8) = 0;
    Thetainfo(1).b(9) = 0;
    Thetainfo(1).b(10) = 0;
    Thetainfo(1).b(11) = 0;
   
    Thetainfo(1).varb(1) = 0;
    Thetainfo(1).varb(2) = 0;
    Thetainfo(1).varb(3) = 0;
    Thetainfo(1).varb(4) = 0;
    Thetainfo(1).varb(5) = 0;
    Thetainfo(1).varb(6) = 0;
    Thetainfo(1).varb(7) = 0;
    Thetainfo(1).varb(8) = 0;
    Thetainfo(1).varb(9) = 0;
    Thetainfo(1).varb(10) = 0;
    Thetainfo(1).varb(11) = 0;
    
else
    bprior(1) = 0;
    bprior(2) = 0;
    bprior(3) = 0;
    bprior(4) = 0;
    bprior(5) = 0;
    bprior(6) = 0;
    bprior(7) = 0;
    bprior(8) = 0;
    bprior(9) = 0;
    bprior(10) = 0;
    bprior(11) = 0;
    
    Sigmabprior(1) = 10;
    Sigmabprior(2) = 10;
    Sigmabprior(3) = 10;
    Sigmabprior(4) = 10;
    Sigmabprior(5) = 10;
    Sigmabprior(6) = 10;
    Sigmabprior(7) = 10;
    Sigmabprior(8) = 10;
    Sigmabprior(9) = 10;
    Sigmabprior(10) = 10;
    Sigmabprior(11) = 10;
    
    atm_sum = 0;
    bank_sum = 0;
    bar_sum = 0;
    cafe_sum = 0;
    ind_sum = 0;
    mark_sum = 0;
    night_sum = 0;
    police_sum = 0; 
    pub_sum = 0;
    rest_sum = 0;
    taxi_sum = 0; 
    
    totalfieldsum = 0;
    
    atm_cont =  @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.atm,s1,s2);
    bank_cont =   @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.bank ,s1,s2);
    bar_cont =  @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.bar,s1,s2);
    cafe_cont =   @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.cafe,s1,s2);
    ind_cont =  @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.ind,s1,s2);
    mark_cont =   @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.mark ,s1,s2);
    night_cont =  @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.night,s1,s2);
    police_cont =   @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.police ,s1,s2);
    pub_cont =  @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.pub,s1,s2);
    rest_cont =   @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.rest ,s1,s2);
    taxi_cont =   @(s1,s2) interp2(Constants.s1,Constants.s2,Constants.taxi ,s1,s2);
    
    Basis_vec_mat = reshape(Basis.phi,[],Basis.nx);
    phitemp = zeros(Constants.J,Constants.J,Basis.nx);
    
    for i = 3:N-2
        Umean = sum(multiprod(Basis.phi,reshape(Estinfo(i).xestRTS,1,1,Basis.nx)),3);
        MySigma = Estinfo(i).PRTS;
        phitemp_vec = Basis_vec_mat*MySigma;
        phitemp = reshape(phitemp_vec,Constants.J,Constants.J,Basis.nx);
        phisigma = sum(phitemp.*Basis.phi,3);
        
        totalfieldsum = totalfieldsum + dt*(exp(Constants.beta*Umean + Constants.beta^2*phisigma./2));
        
        atm_sum = atm_sum + sum(atm_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	bank_sum = bank_sum + sum(bank_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	bar_sum = bar_sum + sum(bar_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	cafe_sum = cafe_sum + sum(cafe_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	ind_sum = ind_sum + sum(ind_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	mark_sum = mark_sum + sum(mark_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	night_sum = night_sum + sum(night_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	police_sum = police_sum + sum(police_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	pub_sum = pub_sum + sum(pub_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	rest_sum = rest_sum + sum(rest_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    	taxi_sum = taxi_sum + sum(taxi_cont(spikes(i).Coords(:,1),spikes(i).Coords(:,2)));
    end
    
    b1int_1 = @(b1) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b1*Constants.atm + Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b1int_2 = @(b1) sum(sum(Constants.atm.*exp(Thetainfo.muest + b1*Constants.atm + Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b1int_3 = @(b1) sum(sum((Constants.atm.^2).*exp(Thetainfo.muest + b1*Constants.atm + Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    
    fb1 = @(b1) -(-(b1 - bprior(1))^2/(2*Sigmabprior(1)) + b1*atm_sum - b1int_1(b1));
    gradfb1 = @(b1) -(-(b1 - bprior(1))/Sigmabprior(1) + atm_sum - b1int_2(b1));
    foptions = [0,1e-4,1e-4,1e-6,0,0,0,0,0,0,0,0,0,0,0,1e-8,0.1,0];
    options = foptions;
    options(9) = 1;
    Thetainfo(1).best(1) = scg(fb1,bprior(1),options,gradfb1)';
    Thetainfo(1).varb(1) = 1/(1/Sigmabprior(1) + b1int_3(Thetainfo(1).best(1)));
    
    
    b2int_1 = @(b2) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b2*Constants.bank + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b2int_2 = @(b2) sum(sum(Constants.bank.*exp(Thetainfo.muest +  b2*Constants.bank + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b2int_3 = @(b2) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b2*Constants.bank + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    
    fb2 = @(b2) -(-(b2 - bprior(2))^2/(2*Sigmabprior(2)) + b2*bank_sum - b2int_1(b2));
    gradfb2 = @(b2) -(-(b2 - bprior(2))/Sigmabprior(2) + bank_sum - b2int_2(b2));
    Thetainfo(1).best(2) = scg(fb2,bprior(2),options,gradfb2)';
    Thetainfo(1).varb(2) = 1/(1/Sigmabprior(2) + b2int_3(Thetainfo(1).best(2)));
    
    b3int_1 = @(b3) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b3*Constants.bar + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b3int_2 = @(b3) sum(sum(Constants.bank.*exp(Thetainfo.muest + b3*Constants.bar + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b3int_3 = @(b3) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b3*Constants.bar + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    
    fb3 = @(b3) -(-(b3 - bprior(3))^2/(2*Sigmabprior(3)) + b3*bar_sum - b3int_1(b3));
    gradfb3 = @(b3) -(-(b3 - bprior(3))/Sigmabprior(3) + bar_sum - b3int_2(b3));
    Thetainfo(1).best(3) = scg(fb3,bprior(3),options,gradfb3)';
    Thetainfo(1).varb(3) = 1/(1/Sigmabprior(3) + b3int_3(Thetainfo(1).best(3)));
    
    b4int_1 = @(b4) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b4*Constants.cafe + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b4int_2 = @(b4) sum(sum(Constants.bank.*exp(Thetainfo.muest + b4*Constants.cafe + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b4int_3 = @(b4) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b4*Constants.cafe + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    
    fb4 = @(b4) -(-(b4 - bprior(4))^2/(2*Sigmabprior(4)) + b4*cafe_sum - b4int_1(b4));
    gradfb4 = @(b4) -(-(b4 - bprior(4))/Sigmabprior(4) + cafe_sum - b4int_2(b4));
    Thetainfo(1).best(4) = scg(fb4,bprior(4),options,gradfb4)';
    Thetainfo(1).varb(4) = 1/(1/Sigmabprior(4) + b4int_3(Thetainfo(1).best(4)));
    
    b5int_1 = @(b5) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b5*Constants.ind + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b5int_2 = @(b5) sum(sum(Constants.bank.*exp(Thetainfo.muest + b5*Constants.ind + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b5int_3 = @(b5) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b5*Constants.ind + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    
    fb5 = @(b5) -(-(b5 - bprior(5))^2/(2*Sigmabprior(5)) + b5*ind_sum - b5int_1(b5));
    gradfb5 = @(b5) -(-(b5 - bprior(5))/Sigmabprior(5) + ind_sum - b5int_2(b5));
    Thetainfo(1).best(5) = scg(fb5,bprior(5),options,gradfb5)';
    Thetainfo(1).varb(5) = 1/(1/Sigmabprior(5) + b5int_3(Thetainfo(1).best(5)));
    
    
    b6int_1 = @(b6) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b6*Constants.mark + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b6int_2 = @(b6) sum(sum(Constants.bank.*exp(Thetainfo.muest + b6*Constants.mark + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b6int_3 = @(b6) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b6*Constants.mark + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    
    fb6 = @(b6) -(-(b6 - bprior(6))^2/(2*Sigmabprior(6)) + b6*mark_sum - b6int_1(b6));
    gradfb6 = @(b6) -(-(b6 - bprior(6))/Sigmabprior(6) + mark_sum - b6int_2(b6));
    Thetainfo(1).best(6) = scg(fb6,bprior(6),options,gradfb6)';
    Thetainfo(1).varb(6) = 1/(1/Sigmabprior(6) + b6int_3(Thetainfo(1).best(6)));
    
    b7int_1 = @(b7) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b7*Constants.night + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b7int_2 = @(b7) sum(sum(Constants.bank.*exp(Thetainfo.muest + b7*Constants.night + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b7int_3 = @(b7) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b7*Constants.night + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
                            
    fb7 = @(b7) -(-(b7 - bprior(7))^2/(2*Sigmabprior(7)) + b7*night_sum - b7int_1(b7));
    gradfb7 = @(b7) -(-(b7 - bprior(7))/Sigmabprior(7) + night_sum - b7int_2(b7));
    Thetainfo(1).best(7) = scg(fb7,bprior(7),options,gradfb7)';
    Thetainfo(1).varb(7) = 1/(1/Sigmabprior(7) + b7int_3(Thetainfo(1).best(7)));
    
    b8int_1 = @(b8) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b8*Constants.police + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b8int_2 = @(b8) sum(sum(Constants.bank.*exp(Thetainfo.muest + b8*Constants.police + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b8int_3 = @(b8) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b8*Constants.police + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(9)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
                            
    fb8 = @(b8) -(-(b8 - bprior(8))^2/(2*Sigmabprior(8)) + b8*police_sum - b8int_1(b8));
    gradfb8 = @(b8) -(-(b8 - bprior(8))/Sigmabprior(8) + police_sum - b8int_2(b8));
    Thetainfo(1).best(8) = scg(fb8,bprior(8),options,gradfb8)';
    Thetainfo(1).varb(8) = 1/(1/Sigmabprior(8) + b8int_3(Thetainfo(1).best(8)));
    
    
    b9int_1 = @(b9) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b9*Constants.pub + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b9int_2 = @(b9) sum(sum(Constants.bank.*exp(Thetainfo.muest + b9*Constants.pub + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b9int_3 = @(b9) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b9*Constants.pub + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
                            
    fb9 = @(b9) -(-(b9 - bprior(9))^2/(2*Sigmabprior(9)) + b9*pub_sum - b9int_1(b9));
    gradfb9 = @(b9) -(-(b9 - bprior(9))/Sigmabprior(9) + pub_sum - b9int_2(b9));
    Thetainfo(1).best(9) = scg(fb9,bprior(9),options,gradfb9)';
    Thetainfo(1).varb(9) = 1/(1/Sigmabprior(9) + b9int_3(Thetainfo(1).best(9)));
    
    
    b10int_1 = @(b10) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b10*Constants.rest + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(10)*Constants.pub.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b10int_2 = @(b10) sum(sum(Constants.bank.*exp(Thetainfo.muest + b10*Constants.rest + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(10)*Constants.pub.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
    b10int_3 = @(b10) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b10*Constants.rest + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(10)*Constants.pub.^2./2 + ...
                                Thetainfo.best(11)*Constants.taxi + Thetainfo.varb(11)*Constants.taxi.^2./2).*totalfieldsum))*Constants.ds^2;
                            
    fb10 = @(b10) -(-(b10 - bprior(10))^2/(2*Sigmabprior(10)) + b10*rest_sum - b10int_1(b10));
    gradfb10 = @(b10) -(-(b10 - bprior(10))/Sigmabprior(10) + rest_sum - b10int_2(b10));
    Thetainfo(1).best(10) = scg(fb10,bprior(10),options,gradfb10)';
    Thetainfo(1).varb(10) = 1/(1/Sigmabprior(10) + b10int_3(Thetainfo(1).best(10)));
    
    
    b11int_1 = @(b11) sum(sum(exp(Thetainfo.muest + Thetainfo.varmu/2 + b11*Constants.taxi + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(10)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2).*totalfieldsum))*Constants.ds^2;
    b11int_2 = @(b11) sum(sum(Constants.bank.*exp(Thetainfo.muest + b11*Constants.taxi + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(10)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2).*totalfieldsum))*Constants.ds^2;
    b11int_3 = @(b11) sum(sum((Constants.bank.^2).*exp(Thetainfo.muest + b11*Constants.taxi + Thetainfo.best(1)*Constants.atm + Thetainfo.varb(1)*Constants.atm.^2./2 + ...
                                Thetainfo.best(2)*Constants.bank + Thetainfo.varb(2)*Constants.bank.^2./2 + ...
                                Thetainfo.best(3)*Constants.bar + Thetainfo.varb(3)*Constants.bar.^2./2 + ...
                                Thetainfo.best(4)*Constants.cafe + Thetainfo.varb(4)*Constants.cafe.^2./2 + ...
                                Thetainfo.best(5)*Constants.ind + Thetainfo.varb(5)*Constants.ind.^2./2 + ...
                                Thetainfo.best(6)*Constants.mark + Thetainfo.varb(6)*Constants.mark.^2./2 + ...
                                Thetainfo.best(7)*Constants.night + Thetainfo.varb(7)*Constants.night.^2./2 + ...
                                Thetainfo.best(8)*Constants.police + Thetainfo.varb(8)*Constants.police.^2./2 + ...
                                Thetainfo.best(9)*Constants.pub + Thetainfo.varb(10)*Constants.pub.^2./2 + ...
                                Thetainfo.best(10)*Constants.rest + Thetainfo.varb(10)*Constants.rest.^2./2).*totalfieldsum))*Constants.ds^2;

    fb11 = @(b11) -(-(b11 - bprior(11))^2/(2*Sigmabprior(11)) + b11*taxi_sum - b11int_1(b11));
    gradfb11 = @(b11) -(-(b11 - bprior(11))/Sigmabprior(11) + taxi_sum - b11int_2(b11));
    Thetainfo(1).best(11) = scg(fb11,bprior(11),options,gradfb11)';
    Thetainfo(1).varb(11) = 1/(1/Sigmabprior(11) + b11int_3(Thetainfo(1).best(11)));
                            
end


Thetainfo(1).precisionest = precest;
Thetainfo(1).varprecision = varprec;
Thetainfo(1).Meanprecmat = Meanprecmat;

end